# Generated by Django 4.0.2 on 2022-02-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='group',
        ),
    ]
