# Generated by Django 4.0.2 on 2022-02-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='size_group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
